### PR TITLE
moved amp_dev module to access; creating some test users for tina

### PR DESCRIPTION
**Pull request by jasperlieber**

### CODE REVIEW

**Comment by jasperlieber** [comment]
hi @a-pasquale  -- ready for review

**Comment by jasperlieber** [comment]
oh sorry, i rebased 1.0.x, so this PR has a couple unrelated commits

**Comment by jasperlieber** [comment]
@a-pasquale @FloQuinn -- just committed code to add the users to the specified affinity groups

**Comment by a-pasquale** [comment]
This PR has some changes that we don't want, looks like there was a rebase that complicates merging now. Could you create a new branch/PR with just the changes to the amp/dev module? Thanks!

**Pull request closed without merging**
