### PR TITLE
D8-1331 (News and Events on Mobile)

### PR DESCRIPTION
**Pull request by laheara143**
Ready For Review.
Added in bootstrap class for News due to mobile version not being lined up.

### CODE REVIEW

**Comment by jasperlieber** [comment]
looks good to me!!! how test on mobile?

**Comment by laheara143** [comment]
> 

You have to inspect the page and then click on the button shown below.
image

**Review by FloQuinn — COMMENTED** [review]
Looks good

**Comment by FloQuinn** [comment]
> looks good to me!!! how test on mobile?

So in a more complicated review, if we wanted to test, how would we do that?

**Pull request merged**
